# Generated by Django 5.2.1 on 2025-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elevator_availability_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zone_2_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_floor_with_lift_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_floor_without_lift_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heavy_furniture_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('light_furniture_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
