# Generated by Django 5.2.1 on 2025-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypricing',
            name='elevator_availability_price',
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='heavy_furniture_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки тяжелой мебели'),
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='light_furniture_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки легкой мебели'),
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='price_per_floor_with_lift_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость подъема за этаж с лифтом'),
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='price_per_floor_without_lift_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость подъема за этаж без лифта'),
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='zone_1_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зона доставки 20км'),
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='zone_2_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зона доставки 40км'),
        ),
    ]
