# Generated by Django 5.2.1 on 2025-06-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliverypricing_elevator_availability_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypricing',
            old_name='price_per_floor_with_lift_price',
            new_name='price_per_floor_with_lift',
        ),
        migrations.RenameField(
            model_name='deliverypricing',
            old_name='price_per_floor_without_lift_price',
            new_name='price_per_floor_without_lift',
        ),
    ]
