# Generated by Django 5.2.1 on 2025-06-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_price_per_floor_with_lift_price_deliverypricing_price_per_floor_with_lift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypricing',
            name='has_lift',
            field=models.BooleanField(default=False, verbose_name='Наличие лифта'),
        ),
    ]
