# Generated by Django 5.2.1 on 2025-06-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverypricing_has_lift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypricing',
            name='has_lift',
        ),
    ]
