# Generated by Django 5.2.1 on 2025-06-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
    ]
