# Generated by Django 5.2.1 on 2025-06-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Обнинск', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house', models.CharField(blank=True, max_length=20, null=True)),
                ('entrance', models.CharField(blank=True, max_length=20, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('needs_elevator', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
