# Generated by Django 5.2.1 on 2025-06-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalAccount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='delivery_cost',
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='floor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='house',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='needs_elevator',
            field=models.BooleanField(default=False, verbose_name='Нужен ли подъем'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
