# Generated by Django 5.2.1 on 2025-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalAccount', '0002_remove_deliveryprofile_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='has_lift',
            field=models.BooleanField(default=False, verbose_name='Наличие лифта'),
        ),
    ]
