# Generated by Django 5.2.1 on 2025-06-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalAccount', '0004_deliveryprofile_delivery_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='delivery_cost',
        ),
    ]
