# Generated by Django 5.2.1 on 2025-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='products',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='products',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
