# Generated by Django 5.2.1 on 2025-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_products_characteristics_products_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hardware',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фурнитура'),
        ),
    ]
