# Generated by Django 5.2.1 on 2025-05-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
