# Generated by Django 5.2.1 on 2025-05-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourPromotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='article',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='name',
        ),
    ]
