# Generated by Django 5.2.1 on 2025-05-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourPromotions', '0004_alter_promotion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акцию', 'verbose_name_plural': 'Товары по Акции'},
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='Товары по акции',
        ),
    ]
