# Generated by Django 5.2.1 on 2025-05-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourPromotions', '0005_alter_promotion_options_alter_promotion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotion',
            table='Promotion',
        ),
    ]
