# Generated by Django 5.2.1 on 2025-05-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки от пользователей сайтом на обратный звонок'},
        ),
    ]
