# Generated by Django 5.2.1 on 2025-05-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartWishlistOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Корзина товаров', 'verbose_name_plural': 'Корзиы товаров'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Текущий заказ', 'verbose_name_plural': 'Текущие заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элементы заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Избранные товары', 'verbose_name_plural': 'Избранных товаров'},
        ),
    ]
