# Generated by Django 5.2.1 on 2025-05-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartWishlistOrders', '0005_alter_cartitem_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Корзина товаров', 'verbose_name_plural': 'Корзины товаров'},
        ),
    ]
